name: Trigger Dependency Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Touch dummy file
        run: |
          echo "Triggering scan at $(date)" >> scan.log
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git init
          git add scan.log
          git commit -m "Trigger dependency graph"
