name: Trigger Dependency Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-22.04  # ✅ Use older stable runner
    steps:
      - uses: actions/checkout@v4

      - name: Force dependency graph
        run: echo "Scan triggered at $(date)" >> scan.log

      - name: Upload dummy file
        uses: actions/upload-artifact@v3  # or @v2 if v3 still fails
        with:
          name: scan-trigger
          path: scan.log
