name: Trigger Dependency Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Force dependency graph
        run: echo "Scan triggered at $(date)" >> scan.log

      - name: Upload dummy file
        uses: actions/upload-artifact@v2  # ✅ Known good version
        with:
          name: scan-trigger
          path: scan.log
